## throw语句抛出异常
throw语句用来抛出一个用户自定义的异常。当前函数的执行将被停止（throw之后的语句将不会执行），并且控制将被传递到调用堆栈中的第一个catch块。
如果调用者函数中没有catch块，程序将会终止。